NewProjectBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.posts_list, name='posts_list'),
    path('posts/<str:category>', views.posts_list, name='posts_list_category'),
    # path('posts/', views.PostListView.as_view, name='posts_list'),
    path('posts/detail/<int:pk>/', views.posts_detail, name='posts_detail'),
    # path('posts/<int:pk>/', views.PostDetailView.as_view, name='posts_detail'),
    path('posts/<post_id>/comment', views.post_comment, name='post_comment'),
    path('ticket', views.ticket, name='ticket'),
    path('profile/create_post/', views.create_post, name='create_post'),
    path('search', views.post_search, name='post_search'),
    path('profile/', views.profile, name='profile'),
    path('profile/delete_post/<post_id>', views.delete_post, name='delete_post'),
    path('profile/edit_post/<post_id>', views.edit_post, name='edit_post'),
    path('profile/delete_image/<image_id>', views.delete_image, name='delete_image'),
    # path('login', views.user_login, name='login'),
    path('logout', views.log_out, name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
         success_url='/blog/password-reset/complete/'), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('register/', views.register, name='register'),

    path('account/edit', views.edit_account, name='edit_account'),

]

blog/forms.py
from django import forms
from .models import Comment, Post, User, Account


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError('شماره تلفن باید عدد باشد!')
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError('نام کوتاه است !')
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']


# class PostForm(forms.Form):
#     author = forms.CharField(required=True, label='نام کاربری')
#     title = forms.CharField(max_length=250, required=True, label='موضوع')
#     description = forms.CharField(widget=forms.Textarea, required=True, label='متن')
#     # reading_time = forms.DateTimeField(label='زمان مطالعه')
#
#     def clean_title(self):
#         title = self.cleaned_data['title']
#         if title:
#             if len(title) > 250:
#                 raise forms.ValidationError('موضوع بسیار طولانی !')
#             else:
#                 return title
#
#     def clean_description(self):
#         description = self.cleaned_data['description']
#         if description:
#             if len(description) < 250:
#                 raise forms.ValidationError('متن پست بسیار کوتاه است !')
#             else:
#                 return description

    # def clean_author(self):
    #     author = self.cleaned_data['author']
    #     exists = User.objects.filter(username='author').exists()
    #     if exists:
    #         user = User.objects.get(username=author)
    #         return user
    #     else:
    #         raise forms.ValidationError('نام کاربری اشتباه است !')
    #


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label='تصویر اول')
    image2 = forms.ImageField(label='تصویر دوم')

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']


class SearchForm(forms.Form):
    query = forms.CharField()


# class LoginForm(forms.Form):
#     user_name = forms.CharField(max_length=250, required=True)
#     password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label='password')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='repeat password')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارد!')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *

# Create your views here.


def index(request):
    return render(request, 'blog/index.html')


def posts_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)

    context = {
        'posts': posts,
        'category': category
    }
    return render(request, 'blog/list.html', context)

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 2
#     template_name = 'blog/list.html'


def posts_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # try:
    #     post = Post.published.get(id=id)
    # except:
    #     raise Http404('Not Post Found !')
    ##
    context = {
        "post": post,
        "form": form,
        "comments": comments
    }
    return render(request, 'blog/detail.html', context)

# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'


def ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'],
                                  phone=cd['phone'], subject=cd['subject'])

            # ticket_obj = Ticket.objects.create()
            # ticket_obj.message = cd['message']
            # ticket_obj.name = cd['name']
            # ticket_obj.email = cd['email']
            # ticket_obj.phone = cd['phone']
            # ticket_obj.subject = cd['subject']
            # ticket_obj.save()

            return redirect('blog:ticket')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, 'forms/comment.html', context)


# def create_post(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user_exist = User.objects.filter(username=cd['author']).exists()
#             if user_exist:
#                 Post.object.create(author=User.objects.get(username="AliAdmin"), title=cd['title'],
#                                    description=cd['description'], publish=timezone.now())
#                 return redirect('blog:create_post')
#             else:
#                 raise Http404('نام کاربری نامعبر است !')
#     else:
#         form = PostForm()
#
#     context = {
#         'form': form
#     }
#     return render(request, 'forms/create_post.html', context)


@login_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            img1 = Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            post.images.add(img1)
            img2 = Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            post.images.add(img2)

            return redirect('blog:profile')
    else:
        form = PostForm()
    return render(request, 'forms/create_post.html', {'form': form})


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_query = SearchQuery(query)
            search_vector = SearchVector('title', 'description')
            results = Post.published.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).\
                filter(search=search_query).order_by('-rank')
    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)

    return render(request, 'blog/profile.html', {'posts': posts})


def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/delete_post.html', {'post': post})


@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm(instance=post)

    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'forms/create_post.html', context)


# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['user_name'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('your account is disable')
#             else:
#                 return HttpResponse('your account not logged in')
#     else:
#         form = LoginForm()
#     return render(request, 'registration/login.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password2'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, instance=request.user.account, files=request.FILES)
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {
        'user_form': user_form,
        'account_form': account_form,
    }
    return render(request, 'registration/edit_account.html', context)

blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% load blog_tags %}
{% block title %}post detail{% endblock %}

{% block content %}
    <h1>post detail</h1>
    <h2>{{ post.title }} </h2>
    <hr>
    <div>
        {% for img in post.images.all %}
            <img width="300px" height="200px" src="{{ img.image_file.url }}" alt="{{ img.title }}">
        {% endfor %}
    </div>
    <hr>
    <p>{{ post.description | markdown }}</p>
    <hr>
    <p><b>by ({{ post.author }})  | </b>{{ post.publish }} </p>
    <hr>

    <div>
    {% with comments.count as cm_count %}
        {{ cm_count }} comment {{ cm_count|pluralize }}
    {% endwith %}
    </div>

    <div>
    {% for cm in comments %}
        {{ cm.body|linebreaks }}
        <br>
        {{ cm.name }}
        {% empty %}
           کامنتی وجود ندارد!
    {% endfor %}
    </div>

    <form method="post" action="{% url 'blog:post_comment' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ثپت کامنت">
    </form>

{% endblock %}

blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% load blog_tags %}
{% block title %}index{% endblock %}

{% block content %}
    <h2>آمار</h2>
    <p>{% total_posts %}: تعداد پست </p>
    <br>
    <p>{% total_comment %}: تعداد کامنت </p>
    <br>
    <p>{% last_post_date %}: تاریخ آخرین پست  </p>
    <hr>
    {% latest_posts 5 %}

    <h2>محبوب ترین پست ها</h2>
    {% most_popular_posts as pop_posts %}
    {% for post in pop_posts %}
        <br>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}: with {{ post.comment_count }} comments</a>

    {% endfor %}

    <hr>
    {% max_reading_time as max_time %}
    {% for max in max_time %}
        <p><a href="{{ max.get_absolute_url }}">{{ max.title }}:{{ max.reading_time }}</a>بیشترین زمان مطالعه: </p>
    {% endfor %}

    <hr>
    {% min_reding_time as min_time%}
    {% for min in min_time %}
        <p><a href="{{ min.get_absolute_url }}">{{ min.title }}:{{ min.reading_time }}</a> کمترین زمان مطالعه: </p>
    {% endfor %}

    <hr>
    <h3>فعال ترین نویسنده ها</h3>
    {% most_popular_user as pop_user %}
    {% for p_user in pop_user %}
        <p><a href="{{ p_user.get_absolute_url }}">{{ p_user.username }}:{{ p_user.max_posts }}</a></p>
    {% endfor %}
{% endblock %}

blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% block title %} post list {% endblock %}
{% block content %}
    <h1>post list</h1>

    {% for post in posts %}
        <h2>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p> {{ post.description | truncatewords:4 }}</p>

        <img src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
    {% endfor %}

    {% include 'partials/pagination.html' with page=posts %}
{#    page_obj#}

{% endblock %}

blog/templates/blog/profile.html
{% extends 'parent/base.html' %}
{% block title %} Profile {% endblock %}
{% block content %}

    <p><a href="{% url 'blog:create_post' %}">ایجاد پست جدید</a></p>

    <table style="width: 80%; border: 2px solid black; text-align: right; direction: rtl">
        <tr>
            <th>ردیف</th>
            <th>پست</th>
            <th>مشاهده</th>
            <th>ویرایش</th>
            <th>حذف</th>
        </tr>
        {% for post in posts %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ post.title }}</td>
                <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
                <td><a href="{% url 'blog:edit_post' post.id %}">ویرایش</a></td>
                <td><a href="{% url 'blog:delete_post' post.id %}">حذف</a></td>
            </tr>
        {% endfor %}
    </table>


    <a href="{% url 'blog:edit_account' %}" >تغییر اطلاعات</a>
    <br>
    <br>
    <a href="{% url "blog:password_change" %}"> تغییر پسورد </a>
    <br>
    <br>
    <a href="{% url 'blog:logout' %}">خروج</a>

{% endblock %}

blog/templates/blog/search.html
{% extends 'parent/base.html' %}
{% block title %}post search{% endblock %}
{% block content %}
    {% if query %}
       {{ results.count }} :{{ query }}نتایج جستجو برای:
    {% endif %}
    <br>
    {% for post in results %}
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        <p>{{ post.description }}</p>
    {% empty %}
        نتیجه ای یافت نشد!
    {% endfor %}
{% endblock %}